services:
  django-freelancer:
    build:
      context: .
    ports:
      - "8000:8000"
    environment:
      - DJANGO_KEY=${DJANGO_KEY}
      - DJANGO_DEBUG=${DJANGO_DEBUG}
      - DJANGO_ALLOWED_HOSTS=${DJANGO_ALLOWED_HOSTS}
      - DJANGO_INTERNAL_IPS=${DJANGO_INTERNAL_IPS}
      - DJANGO_ALLOW_REVERSE=${DJANGO_ALLOW_REVERSE}

      - REDIS_PASSWORD=${REDIS_PASSWORD}
      - REDIS_USER=${REDIS_USER}
      - REDIS_USER_PASSWORD=${REDIS_USER_PASSWORD}

      - POSTGRES_DB=${POSTGRES_DB}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}

      - BUCKET_NAME=${BUCKET_NAME}
      - JWT_KEY_PATH=${JWT_KEY_PATH}
    volumes:
      - ./freelancer:/freelancer
    command: >
      sh -c '
        python manage.py makemigrations &&
        python manage.py migrate &&
        python manage.py collectstatic &&
        mkdir "media/" &
        mkdir "media/tmp/" &
        python manage.py runserver 0.0.0.0:8000
      '
    depends_on:
      redis:
        condition: service_healthy
      database:
          condition: service_healthy

  database:
    image: postgres:14.6-alpine
    environment:
      - POSTGRES_DB=${POSTGRES_DB}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
    volumes:
      - postgres_data:/var/lib/postgresql/data
    hostname: postgresdb
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U $POSTGRES_USER -d $POSTGRES_DB"]
      interval: 5s
      retries: 5

  redis:
    image: redis:latest
    container_name: redis_container
    environment:
      - REDIS_PASSWORD=${REDIS_PASSWORD}
      - REDIS_USER=${REDIS_USER}
      - REDIS_USER_PASSWORD=${REDIS_USER_PASSWORD}
    ports:
      - "6379:6379"
    volumes:
      - ./redisdata:/data
    deploy:
      resources:
        limits:
          cpus: '0.50'
          memory: 512M
        reservations:
          cpus: '0.25'
          memory: 256M
    command: >
      sh -c '
        mkdir -p /usr/local/etc/redis &&
        echo "bind 0.0.0.0" > /usr/local/etc/redis/redis.conf &&
        echo "requirepass $REDIS_PASSWORD" >> /usr/local/etc/redis/redis.conf &&
        echo "appendonly yes" >> /usr/local/etc/redis/redis.conf &&
        echo "appendfsync everysec" >> /usr/local/etc/redis/redis.conf &&
        echo "user default on nopass ~* &* +@all" > /usr/local/etc/redis/users.acl &&
        echo "user $REDIS_USER on >$REDIS_USER_PASSWORD ~* &* +@all" >> /usr/local/etc/redis/users.acl &&
        redis-server /usr/local/etc/redis/redis.conf --aclfile /usr/local/etc/redis/users.acl
      '
    healthcheck:
      test: [ "CMD", "redis-cli", "-a", "$REDIS_PASSWORD", "ping" ]
      interval: 5s
      timeout: 5s
      retries: 5
    restart: unless-stopped
    tty: true
    stdin_open: true

  worker:
    build:
      context: .
    environment:
      - REDIS_PASSWORD=${REDIS_PASSWORD}
      - REDIS_USER=${REDIS_USER}
      - REDIS_USER_PASSWORD=${REDIS_USER_PASSWORD}
      - JWT_KEY_PATH=${JWT_KEY_PATH}
    hostname: worker
    entrypoint: celery
    command:
      -A celery_app.app worker --loglevel=info
    volumes:
      - ./freelancer:/freelancer
    links:
      - redis
    depends_on:
      - redis

  beat:
    build:
      context: .
    environment:
      - REDIS_PASSWORD=${REDIS_PASSWORD}
      - REDIS_USER=${REDIS_USER}
      - REDIS_USER_PASSWORD=${REDIS_USER_PASSWORD}
      - JWT_KEY_PATH=${JWT_KEY_PATH}
    hostname: beat
    entrypoint: celery
    command:
      -A celery_app.app beat --loglevel=info
    volumes:
      - ./freelancer:/freelancer
    links:
      - redis
    depends_on:
      - redis

  flower:
    build:
      context: .
    environment:
      - REDIS_PASSWORD=${REDIS_PASSWORD}
      - REDIS_USER=${REDIS_USER}
      - REDIS_USER_PASSWORD=${REDIS_USER_PASSWORD}
    hostname: flower
    entrypoint: celery
    command:
      -A celery_app.app flower --basic-auth=admin:admin
    volumes:
      - ./freelancer:/freelancer
    links:
      - redis
    depends_on:
      - redis
    ports:
      - "5555:5555"

volumes:
  postgres_data: