# Generated by Django 5.2.12 on 2026-04-27 17:01

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ProjectModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(editable=False)),
                ('name', models.CharField(max_length=254)),
                ('slug', models.SlugField(blank=True, unique=True)),
                ('description', models.TextField()),
                ('customer', models.CharField(max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('status', models.CharField(choices=[('new', 'Новый'), ('in_progress', 'В работе'), ('in_revision', 'На доработке'), ('canceled', 'Отменён'), ('finished', 'Завершён')], default='new', max_length=20)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='projects', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Проект',
                'verbose_name_plural': 'Проекты',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='FileModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.URLField(max_length=2000)),
                ('dirty_file_url', models.URLField(max_length=2000, null=True)),
                ('filename', models.CharField(max_length=254)),
                ('slug', models.SlugField(blank=True, unique=True)),
                ('readable_filename', models.CharField(max_length=254)),
                ('bucket', models.CharField(max_length=63)),
                ('object_path', models.CharField(max_length=2000)),
                ('upload_id', models.UUIDField(editable=False, null=True)),
                ('extension', models.CharField(max_length=8)),
                ('version', models.PositiveIntegerField(default=0)),
                ('version_comment', models.TextField()),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('project', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='files', to='projects.projectmodel')),
            ],
            options={
                'verbose_name': 'Файл',
                'verbose_name_plural': 'Файлы',
                'ordering': ['-version'],
            },
        ),
    ]
