# Generated by Django 5.2.12 on 2026-04-27 17:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projectmodel',
            name='uuid',
            field=models.CharField(editable=False, max_length=36),
        ),
    ]
