# Generated by Django 5.2.12 on 2026-04-23 14:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0002_projectmodel_id_alter_projectmodel_uuid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='filemodel',
            name='project',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='files', to='projects.projectmodel'),
        ),
    ]
