# Generated by Django 5.2.12 on 2026-04-23 14:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0003_alter_filemodel_project'),
    ]

    operations = [
        migrations.AlterField(
            model_name='filemodel',
            name='upload_id',
            field=models.UUIDField(editable=False),
        ),
    ]
