# Generated by Django 5.2.12 on 2026-04-26 13:23

from django.db import migrations, models


def fill_bucket_and_object_path(apps, schema_editor):
    FileModel = apps.get_model('projects', 'FileModel')

    for obj in FileModel.objects.all():
        if obj.url:
            raw_data = obj.url.replace("https://storage.yandexcloud.net/", "").rstrip("/").split("/")
            obj.bucket = raw_data[0]
            obj.object_path = "/".join(raw_data[1:])
            obj.save()


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0004_alter_filemodel_upload_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='filemodel',
            name='bucket',
            field=models.CharField(max_length=63, null=True),
        ),
        migrations.AddField(
            model_name='filemodel',
            name='object_path',
            field=models.CharField(max_length=2000, null=True),
        ),
        migrations.AlterField(
            model_name='filemodel',
            name='url',
            field=models.URLField(max_length=2000),
        ),
        migrations.RunPython(fill_bucket_and_object_path),
    ]
