# Generated by Django 5.2.12 on 2026-04-26 13:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0005_filemodel_bucket_filemodel_object_path_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='filemodel',
            name='bucket',
            field=models.CharField(max_length=63),
        ),
        migrations.AlterField(
            model_name='filemodel',
            name='object_path',
            field=models.CharField(max_length=2000),
        ),
    ]
