# Generated by Django 5.2.12 on 2026-04-26 17:48
import random

from django.db import migrations, models


def random_slug(apps, schema_editor):
    FileModel = apps.get_model('projects', 'FileModel')

    for obj in FileModel.objects.all():
        obj.slug = random.randint(1000, 9999)
        obj.save()


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0006_alter_filemodel_bucket_alter_filemodel_object_path'),
    ]

    operations = [
        migrations.AddField(
            model_name='filemodel',
            name='slug',
            field=models.SlugField(blank=True),
        ),
        migrations.RunPython(random_slug),
    ]
