# Generated by Django 5.2.12 on 2026-04-26 17:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0007_filemodel_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='filemodel',
            name='slug',
            field=models.SlugField(blank=True, unique=True),
        ),
    ]
