# Generated by Django 5.2.12 on 2026-04-26 18:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0009_alter_filemodel_version_comment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='filemodel',
            name='upload_id',
            field=models.UUIDField(editable=False, null=True),
        ),
    ]
