# Generated by Django 5.2.12 on 2026-04-26 18:58

from django.db import migrations, models


def url_to_dirty_file_url(apps, schema_editor):
    FileModel = apps.get_model('projects', 'FileModel')

    for obj in FileModel.objects.all():
        obj.dirty_file_url = obj.url
        obj.save()


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0010_alter_filemodel_upload_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='filemodel',
            name='dirty_file_url',
            field=models.URLField(max_length=2000, null=True),
        ),
        migrations.RunPython(url_to_dirty_file_url),
    ]
